### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by cbrnr** [xdf-modules/libxdf#34]
Are you down for renaming master -> main? I did this multiple times in other repos and it worked without any issues.

**Comment by Yida-Lin** [comment]
Hi @cbrnr , sure sounds good to me!

Seems there are a few warnings though; seems not a big deal, but wanted to post them here just to be sure

![image](https://user-images.githubusercontent.com/20526646/135129728-250d5f52-6908-478a-8db6-5aa8ffe8b293.png)

**Comment by cbrnr** [comment]
Do you have time to look at the GitHub Pages issue?

**Comment by Yida-Lin** [comment]
Probably need to wait until later today. Looks like it says "a new commit" but didn't specify which one. If you have a moment, would you mind giving a quick try? In the worst case we can revert

Thanks

![image](https://user-images.githubusercontent.com/20526646/135133299-dedd2d44-13c8-45cb-b61c-4c3af5a0f892.png)

**Comment by cbrnr** [comment]
Sure, I think it worked. Please double-check and if everything is fine close this issue.

**Comment by Yida-Lin** [comment]
Just tested and it worked great! Thanks @cbrnr
